version: '3'
services:
  nuxt-app:
    build: .  # Dockerfileの場所
    working_dir: /src  # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - .:/src
    ports:
      - 5000:3000   # コンテナ内部の3000を外部から5000でアクセスする
    tty: true   # コンテナ起動後、StatusがExitにならないようttyの設定